// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rpc/server.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CLI_Join_FullMethodName                    = "/rpc.CLI/Join"
	CLI_Leave_FullMethodName                   = "/rpc.CLI/Leave"
	CLI_Status_FullMethodName                  = "/rpc.CLI/Status"
	CLI_Promote_FullMethodName                 = "/rpc.CLI/Promote"
	CLI_SetMode_FullMethodName                 = "/rpc.CLI/SetMode"
	CLI_UpdateConfig_FullMethodName            = "/rpc.CLI/UpdateConfig"
	CLI_ResyncNetwork_FullMethodName           = "/rpc.CLI/ResyncNetwork"
	CLI_CreateCluster_FullMethodName           = "/rpc.CLI/CreateCluster"
	CLI_Token_FullMethodName                   = "/rpc.CLI/Token"
	CLI_CreateGroup_FullMethodName             = "/rpc.CLI/CreateGroup"
	CLI_AddIPToGroup_FullMethodName            = "/rpc.CLI/AddIPToGroup"
	CLI_RemoveIPFromGroup_FullMethodName       = "/rpc.CLI/RemoveIPFromGroup"
	CLI_AssignGroupToNode_FullMethodName       = "/rpc.CLI/AssignGroupToNode"
	CLI_UnassignGroupFromNode_FullMethodName   = "/rpc.CLI/UnassignGroupFromNode"
	CLI_DeleteGroup_FullMethodName             = "/rpc.CLI/DeleteGroup"
	CLI_ListGroups_FullMethodName              = "/rpc.CLI/ListGroups"
	CLI_InitiateJoin_FullMethodName            = "/rpc.CLI/InitiateJoin"
	CLI_GetVotingSessions_FullMethodName       = "/rpc.CLI/GetVotingSessions"
	CLI_GetVotingSessionDetails_FullMethodName = "/rpc.CLI/GetVotingSessionDetails"
)

// CLIClient is the client API for CLI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CLI Service
// -----------------------------------------------------------------------------
// This service is primarily the daemon-local API that `pulsectl` calls on
// 127.0.0.1. It also contains a small number of RPCs that are invoked by
// other nodes during membership operations.
//
// Organization of methods below:
//   - Membership (remote-target): called by other nodes to join/leave.
//   - Daemon-local admin: used by the local CLI to manage the node/cluster.
//   - Group management: CRUD and assignment for floating IP groups.
//   - Orchestration (local-only): helpers that orchestrate multi-step flows
//     while keeping pulsectl connectivity local-only.
//   - Quorum info: read-only inspection of voting sessions.
type CLIClient interface {
	// Membership (remote-target)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
	// Daemon-local admin
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	SetMode(ctx context.Context, in *SetModeRequest, opts ...grpc.CallOption) (*SetModeResponse, error)
	// Config updates
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	// Network resync
	ResyncNetwork(ctx context.Context, in *ResyncNetworkRequest, opts ...grpc.CallOption) (*ResyncNetworkResponse, error)
	// Cluster lifecycle
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error)
	// Token management
	Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// Group management
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	AddIPToGroup(ctx context.Context, in *AddIPToGroupRequest, opts ...grpc.CallOption) (*AddIPToGroupResponse, error)
	RemoveIPFromGroup(ctx context.Context, in *RemoveIPFromGroupRequest, opts ...grpc.CallOption) (*RemoveIPFromGroupResponse, error)
	AssignGroupToNode(ctx context.Context, in *AssignGroupRequest, opts ...grpc.CallOption) (*AssignGroupResponse, error)
	UnassignGroupFromNode(ctx context.Context, in *UnassignGroupRequest, opts ...grpc.CallOption) (*UnassignGroupResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	// Orchestration (local-only)
	// Initiate a server-driven join against a target member
	InitiateJoin(ctx context.Context, in *InitiateJoinRequest, opts ...grpc.CallOption) (*InitiateJoinResponse, error)
	// Quorum info (read-only)
	GetVotingSessions(ctx context.Context, in *GetVotingSessionsRequest, opts ...grpc.CallOption) (*GetVotingSessionsResponse, error)
	GetVotingSessionDetails(ctx context.Context, in *GetVotingSessionDetailsRequest, opts ...grpc.CallOption) (*GetVotingSessionDetailsResponse, error)
}

type cLIClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIClient(cc grpc.ClientConnInterface) CLIClient {
	return &cLIClient{cc}
}

func (c *cLIClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, CLI_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, CLI_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CLI_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, CLI_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) SetMode(ctx context.Context, in *SetModeRequest, opts ...grpc.CallOption) (*SetModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetModeResponse)
	err := c.cc.Invoke(ctx, CLI_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, CLI_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) ResyncNetwork(ctx context.Context, in *ResyncNetworkRequest, opts ...grpc.CallOption) (*ResyncNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResyncNetworkResponse)
	err := c.cc.Invoke(ctx, CLI_ResyncNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClusterResponse)
	err := c.cc.Invoke(ctx, CLI_CreateCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, CLI_Token_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, CLI_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) AddIPToGroup(ctx context.Context, in *AddIPToGroupRequest, opts ...grpc.CallOption) (*AddIPToGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddIPToGroupResponse)
	err := c.cc.Invoke(ctx, CLI_AddIPToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) RemoveIPFromGroup(ctx context.Context, in *RemoveIPFromGroupRequest, opts ...grpc.CallOption) (*RemoveIPFromGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveIPFromGroupResponse)
	err := c.cc.Invoke(ctx, CLI_RemoveIPFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) AssignGroupToNode(ctx context.Context, in *AssignGroupRequest, opts ...grpc.CallOption) (*AssignGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignGroupResponse)
	err := c.cc.Invoke(ctx, CLI_AssignGroupToNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) UnassignGroupFromNode(ctx context.Context, in *UnassignGroupRequest, opts ...grpc.CallOption) (*UnassignGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignGroupResponse)
	err := c.cc.Invoke(ctx, CLI_UnassignGroupFromNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGroupResponse)
	err := c.cc.Invoke(ctx, CLI_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, CLI_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) InitiateJoin(ctx context.Context, in *InitiateJoinRequest, opts ...grpc.CallOption) (*InitiateJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateJoinResponse)
	err := c.cc.Invoke(ctx, CLI_InitiateJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) GetVotingSessions(ctx context.Context, in *GetVotingSessionsRequest, opts ...grpc.CallOption) (*GetVotingSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVotingSessionsResponse)
	err := c.cc.Invoke(ctx, CLI_GetVotingSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) GetVotingSessionDetails(ctx context.Context, in *GetVotingSessionDetailsRequest, opts ...grpc.CallOption) (*GetVotingSessionDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVotingSessionDetailsResponse)
	err := c.cc.Invoke(ctx, CLI_GetVotingSessionDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLIServer is the server API for CLI service.
// All implementations must embed UnimplementedCLIServer
// for forward compatibility.
//
// CLI Service
// -----------------------------------------------------------------------------
// This service is primarily the daemon-local API that `pulsectl` calls on
// 127.0.0.1. It also contains a small number of RPCs that are invoked by
// other nodes during membership operations.
//
// Organization of methods below:
//   - Membership (remote-target): called by other nodes to join/leave.
//   - Daemon-local admin: used by the local CLI to manage the node/cluster.
//   - Group management: CRUD and assignment for floating IP groups.
//   - Orchestration (local-only): helpers that orchestrate multi-step flows
//     while keeping pulsectl connectivity local-only.
//   - Quorum info: read-only inspection of voting sessions.
type CLIServer interface {
	// Membership (remote-target)
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Leave(context.Context, *LeaveRequest) (*LeaveResponse, error)
	// Daemon-local admin
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	SetMode(context.Context, *SetModeRequest) (*SetModeResponse, error)
	// Config updates
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	// Network resync
	ResyncNetwork(context.Context, *ResyncNetworkRequest) (*ResyncNetworkResponse, error)
	// Cluster lifecycle
	CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error)
	// Token management
	Token(context.Context, *TokenRequest) (*TokenResponse, error)
	// Group management
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	AddIPToGroup(context.Context, *AddIPToGroupRequest) (*AddIPToGroupResponse, error)
	RemoveIPFromGroup(context.Context, *RemoveIPFromGroupRequest) (*RemoveIPFromGroupResponse, error)
	AssignGroupToNode(context.Context, *AssignGroupRequest) (*AssignGroupResponse, error)
	UnassignGroupFromNode(context.Context, *UnassignGroupRequest) (*UnassignGroupResponse, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	// Orchestration (local-only)
	// Initiate a server-driven join against a target member
	InitiateJoin(context.Context, *InitiateJoinRequest) (*InitiateJoinResponse, error)
	// Quorum info (read-only)
	GetVotingSessions(context.Context, *GetVotingSessionsRequest) (*GetVotingSessionsResponse, error)
	GetVotingSessionDetails(context.Context, *GetVotingSessionDetailsRequest) (*GetVotingSessionDetailsResponse, error)
	mustEmbedUnimplementedCLIServer()
}

// UnimplementedCLIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCLIServer struct{}

func (UnimplementedCLIServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedCLIServer) Leave(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedCLIServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedCLIServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedCLIServer) SetMode(context.Context, *SetModeRequest) (*SetModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedCLIServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedCLIServer) ResyncNetwork(context.Context, *ResyncNetworkRequest) (*ResyncNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResyncNetwork not implemented")
}
func (UnimplementedCLIServer) CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCluster not implemented")
}
func (UnimplementedCLIServer) Token(context.Context, *TokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Token not implemented")
}
func (UnimplementedCLIServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedCLIServer) AddIPToGroup(context.Context, *AddIPToGroupRequest) (*AddIPToGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIPToGroup not implemented")
}
func (UnimplementedCLIServer) RemoveIPFromGroup(context.Context, *RemoveIPFromGroupRequest) (*RemoveIPFromGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIPFromGroup not implemented")
}
func (UnimplementedCLIServer) AssignGroupToNode(context.Context, *AssignGroupRequest) (*AssignGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignGroupToNode not implemented")
}
func (UnimplementedCLIServer) UnassignGroupFromNode(context.Context, *UnassignGroupRequest) (*UnassignGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignGroupFromNode not implemented")
}
func (UnimplementedCLIServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedCLIServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedCLIServer) InitiateJoin(context.Context, *InitiateJoinRequest) (*InitiateJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateJoin not implemented")
}
func (UnimplementedCLIServer) GetVotingSessions(context.Context, *GetVotingSessionsRequest) (*GetVotingSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVotingSessions not implemented")
}
func (UnimplementedCLIServer) GetVotingSessionDetails(context.Context, *GetVotingSessionDetailsRequest) (*GetVotingSessionDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVotingSessionDetails not implemented")
}
func (UnimplementedCLIServer) mustEmbedUnimplementedCLIServer() {}
func (UnimplementedCLIServer) testEmbeddedByValue()             {}

// UnsafeCLIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLIServer will
// result in compilation errors.
type UnsafeCLIServer interface {
	mustEmbedUnimplementedCLIServer()
}

func RegisterCLIServer(s grpc.ServiceRegistrar, srv CLIServer) {
	// If the following call pancis, it indicates UnimplementedCLIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CLI_ServiceDesc, srv)
}

func _CLI_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).SetMode(ctx, req.(*SetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_ResyncNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResyncNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).ResyncNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_ResyncNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).ResyncNetwork(ctx, req.(*ResyncNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_CreateCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).CreateCluster(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_Token_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Token(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_AddIPToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIPToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).AddIPToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_AddIPToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).AddIPToGroup(ctx, req.(*AddIPToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_RemoveIPFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIPFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).RemoveIPFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_RemoveIPFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).RemoveIPFromGroup(ctx, req.(*RemoveIPFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_AssignGroupToNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).AssignGroupToNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_AssignGroupToNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).AssignGroupToNode(ctx, req.(*AssignGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_UnassignGroupFromNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).UnassignGroupFromNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_UnassignGroupFromNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).UnassignGroupFromNode(ctx, req.(*UnassignGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_InitiateJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).InitiateJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_InitiateJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).InitiateJoin(ctx, req.(*InitiateJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_GetVotingSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVotingSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).GetVotingSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_GetVotingSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).GetVotingSessions(ctx, req.(*GetVotingSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_GetVotingSessionDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVotingSessionDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).GetVotingSessionDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLI_GetVotingSessionDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).GetVotingSessionDetails(ctx, req.(*GetVotingSessionDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CLI_ServiceDesc is the grpc.ServiceDesc for CLI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.CLI",
	HandlerType: (*CLIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _CLI_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _CLI_Leave_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _CLI_Status_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _CLI_Promote_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _CLI_SetMode_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _CLI_UpdateConfig_Handler,
		},
		{
			MethodName: "ResyncNetwork",
			Handler:    _CLI_ResyncNetwork_Handler,
		},
		{
			MethodName: "CreateCluster",
			Handler:    _CLI_CreateCluster_Handler,
		},
		{
			MethodName: "Token",
			Handler:    _CLI_Token_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _CLI_CreateGroup_Handler,
		},
		{
			MethodName: "AddIPToGroup",
			Handler:    _CLI_AddIPToGroup_Handler,
		},
		{
			MethodName: "RemoveIPFromGroup",
			Handler:    _CLI_RemoveIPFromGroup_Handler,
		},
		{
			MethodName: "AssignGroupToNode",
			Handler:    _CLI_AssignGroupToNode_Handler,
		},
		{
			MethodName: "UnassignGroupFromNode",
			Handler:    _CLI_UnassignGroupFromNode_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _CLI_DeleteGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _CLI_ListGroups_Handler,
		},
		{
			MethodName: "InitiateJoin",
			Handler:    _CLI_InitiateJoin_Handler,
		},
		{
			MethodName: "GetVotingSessions",
			Handler:    _CLI_GetVotingSessions_Handler,
		},
		{
			MethodName: "GetVotingSessionDetails",
			Handler:    _CLI_GetVotingSessionDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/server.proto",
}

const (
	Server_ConfigSync_FullMethodName         = "/rpc.Server/ConfigSync"
	Server_MakePassive_FullMethodName        = "/rpc.Server/MakePassive"
	Server_BringUpIP_FullMethodName          = "/rpc.Server/BringUpIP"
	Server_BringDownIP_FullMethodName        = "/rpc.Server/BringDownIP"
	Server_HealthCheck_FullMethodName        = "/rpc.Server/HealthCheck"
	Server_Logs_FullMethodName               = "/rpc.Server/Logs"
	Server_Remove_FullMethodName             = "/rpc.Server/Remove"
	Server_StartVotingSession_FullMethodName = "/rpc.Server/StartVotingSession"
	Server_CastVote_FullMethodName           = "/rpc.Server/CastVote"
	Server_GetVotingResult_FullMethodName    = "/rpc.Server/GetVotingResult"
)

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Server Service
// -----------------------------------------------------------------------------
// Inter-node service used for state synchronization, quorum voting, and
// operational actions (IP bring up/down, health checks, removal, etc.).
type ServerClient interface {
	ConfigSync(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (*ConfigSyncResponse, error)
	MakePassive(ctx context.Context, in *MakePassiveRequest, opts ...grpc.CallOption) (*MakePassiveResponse, error)
	BringUpIP(ctx context.Context, in *UpIpRequest, opts ...grpc.CallOption) (*UpIpResponse, error)
	BringDownIP(ctx context.Context, in *DownIpRequest, opts ...grpc.CallOption) (*DownIpResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	// Quorum voting methods
	StartVotingSession(ctx context.Context, in *StartVotingSessionRequest, opts ...grpc.CallOption) (*StartVotingSessionResponse, error)
	CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error)
	GetVotingResult(ctx context.Context, in *GetVotingResultRequest, opts ...grpc.CallOption) (*GetVotingResultResponse, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) ConfigSync(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (*ConfigSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSyncResponse)
	err := c.cc.Invoke(ctx, Server_ConfigSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) MakePassive(ctx context.Context, in *MakePassiveRequest, opts ...grpc.CallOption) (*MakePassiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakePassiveResponse)
	err := c.cc.Invoke(ctx, Server_MakePassive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) BringUpIP(ctx context.Context, in *UpIpRequest, opts ...grpc.CallOption) (*UpIpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpIpResponse)
	err := c.cc.Invoke(ctx, Server_BringUpIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) BringDownIP(ctx context.Context, in *DownIpRequest, opts ...grpc.CallOption) (*DownIpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownIpResponse)
	err := c.cc.Invoke(ctx, Server_BringDownIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Server_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, Server_Logs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, Server_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) StartVotingSession(ctx context.Context, in *StartVotingSessionRequest, opts ...grpc.CallOption) (*StartVotingSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVotingSessionResponse)
	err := c.cc.Invoke(ctx, Server_StartVotingSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CastVoteResponse)
	err := c.cc.Invoke(ctx, Server_CastVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) GetVotingResult(ctx context.Context, in *GetVotingResultRequest, opts ...grpc.CallOption) (*GetVotingResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVotingResultResponse)
	err := c.cc.Invoke(ctx, Server_GetVotingResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
// All implementations must embed UnimplementedServerServer
// for forward compatibility.
//
// Server Service
// -----------------------------------------------------------------------------
// Inter-node service used for state synchronization, quorum voting, and
// operational actions (IP bring up/down, health checks, removal, etc.).
type ServerServer interface {
	ConfigSync(context.Context, *ConfigSyncRequest) (*ConfigSyncResponse, error)
	MakePassive(context.Context, *MakePassiveRequest) (*MakePassiveResponse, error)
	BringUpIP(context.Context, *UpIpRequest) (*UpIpResponse, error)
	BringDownIP(context.Context, *DownIpRequest) (*DownIpResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Logs(context.Context, *LogsRequest) (*LogsResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	// Quorum voting methods
	StartVotingSession(context.Context, *StartVotingSessionRequest) (*StartVotingSessionResponse, error)
	CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error)
	GetVotingResult(context.Context, *GetVotingResultRequest) (*GetVotingResultResponse, error)
	mustEmbedUnimplementedServerServer()
}

// UnimplementedServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerServer struct{}

func (UnimplementedServerServer) ConfigSync(context.Context, *ConfigSyncRequest) (*ConfigSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigSync not implemented")
}
func (UnimplementedServerServer) MakePassive(context.Context, *MakePassiveRequest) (*MakePassiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakePassive not implemented")
}
func (UnimplementedServerServer) BringUpIP(context.Context, *UpIpRequest) (*UpIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BringUpIP not implemented")
}
func (UnimplementedServerServer) BringDownIP(context.Context, *DownIpRequest) (*DownIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BringDownIP not implemented")
}
func (UnimplementedServerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedServerServer) Logs(context.Context, *LogsRequest) (*LogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedServerServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedServerServer) StartVotingSession(context.Context, *StartVotingSessionRequest) (*StartVotingSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVotingSession not implemented")
}
func (UnimplementedServerServer) CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastVote not implemented")
}
func (UnimplementedServerServer) GetVotingResult(context.Context, *GetVotingResultRequest) (*GetVotingResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVotingResult not implemented")
}
func (UnimplementedServerServer) mustEmbedUnimplementedServerServer() {}
func (UnimplementedServerServer) testEmbeddedByValue()                {}

// UnsafeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServer will
// result in compilation errors.
type UnsafeServerServer interface {
	mustEmbedUnimplementedServerServer()
}

func RegisterServerServer(s grpc.ServiceRegistrar, srv ServerServer) {
	// If the following call pancis, it indicates UnimplementedServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Server_ServiceDesc, srv)
}

func _Server_ConfigSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).ConfigSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_ConfigSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).ConfigSync(ctx, req.(*ConfigSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_MakePassive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakePassiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).MakePassive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_MakePassive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).MakePassive(ctx, req.(*MakePassiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_BringUpIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).BringUpIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_BringUpIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).BringUpIP(ctx, req.(*UpIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_BringDownIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).BringDownIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_BringDownIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).BringDownIP(ctx, req.(*DownIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_Logs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Logs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Logs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Logs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_StartVotingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVotingSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).StartVotingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_StartVotingSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).StartVotingSession(ctx, req.(*StartVotingSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_CastVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).CastVote(ctx, req.(*CastVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_GetVotingResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVotingResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetVotingResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_GetVotingResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetVotingResult(ctx, req.(*GetVotingResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Server_ServiceDesc is the grpc.ServiceDesc for Server service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigSync",
			Handler:    _Server_ConfigSync_Handler,
		},
		{
			MethodName: "MakePassive",
			Handler:    _Server_MakePassive_Handler,
		},
		{
			MethodName: "BringUpIP",
			Handler:    _Server_BringUpIP_Handler,
		},
		{
			MethodName: "BringDownIP",
			Handler:    _Server_BringDownIP_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Server_HealthCheck_Handler,
		},
		{
			MethodName: "Logs",
			Handler:    _Server_Logs_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Server_Remove_Handler,
		},
		{
			MethodName: "StartVotingSession",
			Handler:    _Server_StartVotingSession_Handler,
		},
		{
			MethodName: "CastVote",
			Handler:    _Server_CastVote_Handler,
		},
		{
			MethodName: "GetVotingResult",
			Handler:    _Server_GetVotingResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/server.proto",
}
